version: '3.9'

services:
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
